version: '3.2'

services:
  mail:
    build:
      context: ./mail
    environment:
      - CATCHALL_PASSWORD=hello
    volumes:
      - type: volume
        source: cert
        target: /cert
        volume:
          nocopy: true
      - type: volume
        source: mail
        target: /home/catchall/Maildir
        volume:
          nocopy: true
    ports:
      - "2525:25"
      - "587"
      - "143"
      - "993"
  rainloop:
    build:
      context: ./rainloop
    environment:
      - CATCHALL_PASSWORD=hello
    ports:
      - "8080:80"

volumes:
  mail:
  cert:
